<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Property_Agreement_Preparation</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Syncfusion.DocIORenderer.Net.Core" Version="*" />
    <PackageReference Include="Syncfusion.SmartDataExtractor.Net.Core" Version="*" />
    <PackageReference Include="System.Data.OleDb" Version="*" />
  </ItemGroup>

</Project>
